version: '2'
services:
    rendamais-app:
        image: rendamais
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rendamais-postgresql:5432/rendamais
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=rendamais-elasticsearch:9300
        ports:
            - 8080:8080
    rendamais-postgresql:
        extends:
            file: postgresql.yml
            service: rendamais-postgresql
    rendamais-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rendamais-elasticsearch
